### ISSUE TITLE
역할분배

### ISSUE THREAD

**Issue by Joripje** [limjiin/collaboration_practice#1]
역할분배는 어떻게 할까요??

fizzbuzz는 제가 만들어도 될까요?

**Comment by ddouning** [comment]
네 좋아요 그럼 저랑 태환님 introduce.md 맡을게요!!!

**Comment by limjiin** [comment]
넵 알겠습니다!!

**Comment by Joripje** [comment]
introduce 첫날 했던 내용으로 하면 어떨까요??

**Comment by ddouning** [comment]
음 아니면 여기에 각자 한 줄씩 간단히 써볼까요??

**Comment by limjiin** [comment]
네네 좋아요! 한 줄 정도면 될까요?

**Comment by samjinwang** [comment]
암거나 한줄 써볼게요

**Comment by ddouning** [comment]
재경님 체크리스트 이슈 작성 다되었을까요!~?

**Comment by limjiin** [comment]
I'm jin. 
I like taking a walk and watching movies

이런 식으로 작성하면 도리까요?

**Comment by ddouning** [comment]
아맞다,, 영어로 작성하는거 잊고있엇어요 ,, ㅎ
