### ISSUE TITLE
Fizzbuzz.py 작성

### ISSUE THREAD

**Issue by Joripje** [limjiin/collaboration_practice#3]
(edited)
- [x] 3의 배수에서 fizz 출력
- [x] 5의 배수에서 buzz 출력
- [x] 15의 배수에서 fizzbuzz 출력
- [x] py파일 push 후 검토
- [x] py파일 수정, push, 검토

**Comment by limjiin** [comment]
확인했습니다 ~~ 홧ㅌㅇ!!

**Comment by Joripje** [comment]
혹시 체크리스트 고쳐야 될것 있으면 말씀해주세요~

**Comment by limjiin** [comment]
이대로 가면 될 것 같습니다><

**Comment by samjinwang** [comment]
현재는 좋아보여요
