### ISSUE TITLE
Introduce.md 작성

### ISSUE THREAD

**Issue by samjinwang** [limjiin/collaboration_practice#4]
(edited)

태환님
- [x]  팀 전체 소개 한줄 작성
- [x]  팀장님 (지인님) 소개 한줄 작성
- [x]  재경님 소개 한줄 작성
- [x]  md파일 수정, 검토

서윤님
- [x]  서윤님 소개 한줄 작성
- [x]  태환님 소개 한줄 작성
- [x]  마무리 인삿말 작성
- [x] md파일 수정, 검토

**Comment by limjiin** [comment]
확인했습니다~ 이대로 진행하고 
두분이서 체크리스트 나누면 될 것 같아요~~

**Comment by samjinwang** [comment]
그 맨첫번째 이슈나 여기에다가 각자 인삿말 한줄씩 적어주세요!

**Comment by ddouning** [comment]
네~~ 제가 그럼 서윤님 ~ 뒷부분 맡아서 할게요

**Comment by samjinwang** [comment]
그러면 제가 앞에 3개 하겠습니다!

**Comment by limjiin** [comment]
넵 확인했습ㄴ다~~

인삿말:
HI, I'm jin.
I like taking a walk and watching movies.

**Comment by ddouning** [comment]
I'm seoyoon, I am going to watch movie this night.
I look forward to seeing movie!

**Comment by Joripje** [comment]
I'm Jaegyeong, my username is Joripje.
Joripje from synthetic division in korean
I want to be good at Python...

**Comment by samjinwang** [comment]
Hello, this is Tae Kim. I love playing baseball and taking strolls at night
